import type { ConverterTool, ConverterCategoryMeta } from "@/types/converter.types";

// ─── Image Tools (42) ───────────────────────────────────────────────────────

const imageTools: ConverterTool[] = [
  {
    id: "heic-to-webp",
    name: "HEIC to WebP",
    slug: "heic-to-webp",
    category: "image",
    inputFormats: ["heic", "heif"],
    outputFormat: "webp",
    inputMode: "file",
    endpoint: "/api/image/heic-to-webp",
    description: "Convert iPhone HEIC photos to WebP for web use.",
    options: [{ key: "quality", label: "Quality", type: "range", default: 85, min: 1, max: 100, unit: "%" }],
    popular: true,
  },
  {
    id: "heic-to-jpg",
    name: "HEIC to JPG",
    slug: "heic-to-jpg",
    category: "image",
    inputFormats: ["heic", "heif"],
    outputFormat: "jpg",
    inputMode: "file",
    endpoint: "/api/image/heic-to-jpg",
    description: "Convert HEIC photos to universally compatible JPG format.",
    options: [{ key: "quality", label: "Quality", type: "range", default: 85, min: 1, max: 100, unit: "%" }],
    popular: true,
  },
  {
    id: "heic-to-png",
    name: "HEIC to PNG",
    slug: "heic-to-png",
    category: "image",
    inputFormats: ["heic", "heif"],
    outputFormat: "png",
    inputMode: "file",
    endpoint: "/api/image/heic-to-png",
    description: "Convert HEIC photos to lossless PNG format.",
  },
  {
    id: "webp-to-png",
    name: "WebP to PNG",
    slug: "webp-to-png",
    category: "image",
    inputFormats: ["webp"],
    outputFormat: "png",
    inputMode: "file",
    endpoint: "/api/image/webp-to-png",
    description: "Convert WebP images to lossless PNG.",
    popular: true,
  },
  {
    id: "webp-to-jpg",
    name: "WebP to JPG",
    slug: "webp-to-jpg",
    category: "image",
    inputFormats: ["webp"],
    outputFormat: "jpg",
    inputMode: "file",
    endpoint: "/api/image/webp-to-jpg",
    description: "Convert WebP images to JPG format.",
    options: [{ key: "quality", label: "Quality", type: "range", default: 85, min: 1, max: 100, unit: "%" }],
  },
  {
    id: "webp-to-gif",
    name: "WebP to GIF",
    slug: "webp-to-gif",
    category: "image",
    inputFormats: ["webp"],
    outputFormat: "gif",
    inputMode: "file",
    endpoint: "/api/image/webp-to-gif",
    description: "Convert WebP images to animated GIF format.",
  },
  {
    id: "png-to-jpg",
    name: "PNG to JPG",
    slug: "png-to-jpg",
    category: "image",
    inputFormats: ["png"],
    outputFormat: "jpg",
    inputMode: "file",
    endpoint: "/api/image/png-to-jpg",
    description: "Convert PNG images to JPG for smaller file sizes.",
    options: [{ key: "quality", label: "Quality", type: "range", default: 85, min: 1, max: 100, unit: "%" }],
    popular: true,
  },
  {
    id: "png-to-webp",
    name: "PNG to WebP",
    slug: "png-to-webp",
    category: "image",
    inputFormats: ["png"],
    outputFormat: "webp",
    inputMode: "file",
    endpoint: "/api/image/png-to-webp",
    description: "Convert PNG to modern WebP format for faster web pages.",
    options: [{ key: "quality", label: "Quality", type: "range", default: 85, min: 1, max: 100, unit: "%" }],
  },
  {
    id: "png-to-gif",
    name: "PNG to GIF",
    slug: "png-to-gif",
    category: "image",
    inputFormats: ["png"],
    outputFormat: "gif",
    inputMode: "file",
    endpoint: "/api/image/png-to-gif",
    description: "Convert PNG images to GIF format.",
  },
  {
    id: "png-to-bmp",
    name: "PNG to BMP",
    slug: "png-to-bmp",
    category: "image",
    inputFormats: ["png"],
    outputFormat: "bmp",
    inputMode: "file",
    endpoint: "/api/image/png-to-bmp",
    description: "Convert PNG images to Windows BMP format.",
  },
  {
    id: "png-to-tiff",
    name: "PNG to TIFF",
    slug: "png-to-tiff",
    category: "image",
    inputFormats: ["png"],
    outputFormat: "tiff",
    inputMode: "file",
    endpoint: "/api/image/png-to-tiff",
    description: "Convert PNG to TIFF for print and professional workflows.",
  },
  {
    id: "png-to-ico",
    name: "PNG to ICO",
    slug: "png-to-ico",
    category: "image",
    inputFormats: ["png"],
    outputFormat: "ico",
    inputMode: "file",
    endpoint: "/api/image/png-to-ico",
    description: "Convert PNG to ICO for website favicons and app icons.",
    popular: true,
  },
  {
    id: "jpg-to-png",
    name: "JPG to PNG",
    slug: "jpg-to-png",
    category: "image",
    inputFormats: ["jpg", "jpeg"],
    outputFormat: "png",
    inputMode: "file",
    endpoint: "/api/image/jpg-to-png",
    description: "Convert JPG images to lossless PNG format.",
    popular: true,
  },
  {
    id: "jpg-to-webp",
    name: "JPG to WebP",
    slug: "jpg-to-webp",
    category: "image",
    inputFormats: ["jpg", "jpeg"],
    outputFormat: "webp",
    inputMode: "file",
    endpoint: "/api/image/jpg-to-webp",
    description: "Convert JPG to WebP for better web performance.",
    options: [{ key: "quality", label: "Quality", type: "range", default: 85, min: 1, max: 100, unit: "%" }],
  },
  {
    id: "jpg-to-gif",
    name: "JPG to GIF",
    slug: "jpg-to-gif",
    category: "image",
    inputFormats: ["jpg", "jpeg"],
    outputFormat: "gif",
    inputMode: "file",
    endpoint: "/api/image/jpg-to-gif",
    description: "Convert JPG images to GIF format.",
  },
  {
    id: "jpg-to-bmp",
    name: "JPG to BMP",
    slug: "jpg-to-bmp",
    category: "image",
    inputFormats: ["jpg", "jpeg"],
    outputFormat: "bmp",
    inputMode: "file",
    endpoint: "/api/image/jpg-to-bmp",
    description: "Convert JPG images to Windows BMP format.",
  },
  {
    id: "jpg-to-tiff",
    name: "JPG to TIFF",
    slug: "jpg-to-tiff",
    category: "image",
    inputFormats: ["jpg", "jpeg"],
    outputFormat: "tiff",
    inputMode: "file",
    endpoint: "/api/image/jpg-to-tiff",
    description: "Convert JPG to high-quality TIFF for print.",
  },
  {
    id: "gif-to-mp4",
    name: "GIF to MP4",
    slug: "gif-to-mp4",
    category: "image",
    inputFormats: ["gif"],
    outputFormat: "mp4",
    inputMode: "file",
    endpoint: "/api/image/gif-to-mp4",
    description: "Convert animated GIF to MP4 for smaller file size.",
  },
  {
    id: "gif-to-webp",
    name: "GIF to WebP",
    slug: "gif-to-webp",
    category: "image",
    inputFormats: ["gif"],
    outputFormat: "webp",
    inputMode: "file",
    endpoint: "/api/image/gif-to-webp",
    description: "Convert GIF to animated WebP for modern browsers.",
  },
  {
    id: "gif-to-png",
    name: "GIF to PNG",
    slug: "gif-to-png",
    category: "image",
    inputFormats: ["gif"],
    outputFormat: "png",
    inputMode: "file",
    endpoint: "/api/image/gif-to-png",
    description: "Extract the first frame of a GIF as a PNG image.",
  },
  {
    id: "bmp-to-png",
    name: "BMP to PNG",
    slug: "bmp-to-png",
    category: "image",
    inputFormats: ["bmp"],
    outputFormat: "png",
    inputMode: "file",
    endpoint: "/api/image/bmp-to-png",
    description: "Convert BMP images to compressed PNG format.",
  },
  {
    id: "bmp-to-jpg",
    name: "BMP to JPG",
    slug: "bmp-to-jpg",
    category: "image",
    inputFormats: ["bmp"],
    outputFormat: "jpg",
    inputMode: "file",
    endpoint: "/api/image/bmp-to-jpg",
    description: "Convert BMP images to JPG for smaller file sizes.",
    options: [{ key: "quality", label: "Quality", type: "range", default: 85, min: 1, max: 100, unit: "%" }],
  },
  {
    id: "tiff-to-jpg",
    name: "TIFF to JPG",
    slug: "tiff-to-jpg",
    category: "image",
    inputFormats: ["tiff", "tif"],
    outputFormat: "jpg",
    inputMode: "file",
    endpoint: "/api/image/tiff-to-jpg",
    description: "Convert TIFF to web-friendly JPG format.",
    options: [{ key: "quality", label: "Quality", type: "range", default: 85, min: 1, max: 100, unit: "%" }],
  },
  {
    id: "tiff-to-pdf",
    name: "TIFF to PDF",
    slug: "tiff-to-pdf",
    category: "image",
    inputFormats: ["tiff", "tif"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/image/tiff-to-pdf",
    description: "Convert TIFF images to PDF documents.",
  },
  {
    id: "svg-to-png",
    name: "SVG to PNG",
    slug: "svg-to-png",
    category: "image",
    inputFormats: ["svg"],
    outputFormat: "png",
    inputMode: "file",
    endpoint: "/api/image/svg-to-png",
    description: "Convert SVG vector graphics to raster PNG images.",
    options: [
      { key: "scale", label: "Scale", type: "select", default: "2", options: ["1", "2", "3", "4"] },
      { key: "dpi", label: "DPI", type: "select", default: "150", options: ["72", "96", "150", "300"], unit: "dpi" },
    ],
    popular: true,
  },
  {
    id: "svg-to-pdf",
    name: "SVG to PDF",
    slug: "svg-to-pdf",
    category: "image",
    inputFormats: ["svg"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/image/svg-to-pdf",
    description: "Convert SVG vector graphics to PDF documents.",
  },
  {
    id: "svg-to-jpg",
    name: "SVG to JPG",
    slug: "svg-to-jpg",
    category: "image",
    inputFormats: ["svg"],
    outputFormat: "jpg",
    inputMode: "file",
    endpoint: "/api/image/svg-to-jpg",
    description: "Convert SVG vector graphics to JPG raster images.",
    options: [{ key: "quality", label: "Quality", type: "range", default: 85, min: 1, max: 100, unit: "%" }],
  },
  {
    id: "ico-to-png",
    name: "ICO to PNG",
    slug: "ico-to-png",
    category: "image",
    inputFormats: ["ico"],
    outputFormat: "png",
    inputMode: "file",
    endpoint: "/api/image/ico-to-png",
    description: "Extract the largest frame from an ICO file as PNG.",
  },
  {
    id: "ico-to-jpg",
    name: "ICO to JPG",
    slug: "ico-to-jpg",
    category: "image",
    inputFormats: ["ico"],
    outputFormat: "jpg",
    inputMode: "file",
    endpoint: "/api/image/ico-to-jpg",
    description: "Convert ICO icon files to JPG format.",
    options: [{ key: "quality", label: "Quality", type: "range", default: 85, min: 1, max: 100, unit: "%" }],
  },
  {
    id: "mp4-to-gif",
    name: "MP4 to GIF",
    slug: "mp4-to-gif",
    category: "image",
    inputFormats: ["mp4"],
    outputFormat: "gif",
    inputMode: "file",
    endpoint: "/api/image/mp4-to-gif",
    description: "Convert a short MP4 clip to an animated GIF.",
    options: [
      { key: "start", label: "Start (s)", type: "number", default: 0, min: 0 },
      { key: "duration", label: "Duration (s)", type: "number", default: 10, min: 1, max: 60 },
      { key: "fps", label: "FPS", type: "select", default: "12", options: ["8", "12", "15", "24"] },
    ],
    popular: true,
  },
  {
    id: "image-resize",
    name: "Image Resize",
    slug: "image-resize",
    category: "image",
    inputFormats: ["jpg", "jpeg", "png", "webp", "gif", "bmp"],
    outputFormat: "png",
    inputMode: "file",
    endpoint: "/api/image/resize",
    description: "Resize images to specific dimensions while optionally maintaining aspect ratio.",
    options: [
      { key: "width", label: "Width", type: "number", default: 1920, min: 1, unit: "px" },
      { key: "height", label: "Height", type: "number", default: 1080, min: 1, unit: "px" },
      { key: "maintain_ratio", label: "Maintain ratio", type: "toggle", default: true },
    ],
  },
  {
    id: "image-compress",
    name: "Image Compress",
    slug: "image-compress",
    category: "image",
    inputFormats: ["jpg", "jpeg", "png", "webp"],
    outputFormat: "jpg",
    inputMode: "file",
    endpoint: "/api/image/compress",
    description: "Reduce image file size while preserving visual quality.",
    options: [{ key: "quality", label: "Quality", type: "range", default: 60, min: 1, max: 100, unit: "%" }],
    popular: true,
  },
  {
    id: "raw-to-jpg",
    name: "RAW to JPG",
    slug: "raw-to-jpg",
    category: "image",
    inputFormats: ["raw", "cr2", "nef", "arw", "dng"],
    outputFormat: "jpg",
    inputMode: "file",
    endpoint: "/api/image/raw-to-jpg",
    description: "Convert camera RAW files to JPG via Pillow.",
    options: [{ key: "quality", label: "Quality", type: "range", default: 90, min: 1, max: 100, unit: "%" }],
  },
];

// ─── Document Tools (26) ─────────────────────────────────────────────────────

const documentTools: ConverterTool[] = [
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    slug: "pdf-to-word",
    category: "document",
    inputFormats: ["pdf"],
    outputFormat: "docx",
    inputMode: "file",
    endpoint: "/api/document/pdf-to-word",
    description: "Convert PDF documents to editable Word DOCX files.",
    popular: true,
  },
  {
    id: "pdf-to-txt",
    name: "PDF to Text",
    slug: "pdf-to-txt",
    category: "document",
    inputFormats: ["pdf"],
    outputFormat: "txt",
    inputMode: "file",
    endpoint: "/api/document/pdf-to-txt",
    description: "Extract all text content from a PDF document.",
    popular: true,
  },
  {
    id: "pdf-to-html",
    name: "PDF to HTML",
    slug: "pdf-to-html",
    category: "document",
    inputFormats: ["pdf"],
    outputFormat: "html",
    inputMode: "file",
    endpoint: "/api/document/pdf-to-html",
    description: "Convert PDF to HTML for web embedding.",
  },
  {
    id: "pdf-to-images",
    name: "PDF to Images",
    slug: "pdf-to-images",
    category: "document",
    inputFormats: ["pdf"],
    outputFormat: "zip",
    inputMode: "file",
    endpoint: "/api/document/pdf-to-images",
    description: "Convert each PDF page to a PNG image, delivered as a ZIP.",
    options: [
      { key: "dpi", label: "DPI", type: "select", default: "150", options: ["72", "96", "150", "300"], unit: "dpi" },
    ],
  },
  {
    id: "pdf-merge",
    name: "PDF Merge",
    slug: "pdf-merge",
    category: "document",
    inputFormats: ["pdf"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/document/pdf-merge",
    description: "Combine multiple PDF files into one document.",
    popular: true,
  },
  {
    id: "pdf-split",
    name: "PDF Split",
    slug: "pdf-split",
    category: "document",
    inputFormats: ["pdf"],
    outputFormat: "zip",
    inputMode: "file",
    endpoint: "/api/document/pdf-split",
    description: "Split a PDF into individual pages, delivered as a ZIP.",
  },
  {
    id: "pdf-compress",
    name: "PDF Compress",
    slug: "pdf-compress",
    category: "document",
    inputFormats: ["pdf"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/document/pdf-compress",
    description: "Reduce PDF file size while maintaining quality.",
    popular: true,
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    slug: "word-to-pdf",
    category: "document",
    inputFormats: ["docx", "doc"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/document/word-to-pdf",
    description: "Convert Word documents to PDF using LibreOffice.",
    popular: true,
  },
  {
    id: "word-to-odt",
    name: "Word to ODT",
    slug: "word-to-odt",
    category: "document",
    inputFormats: ["docx", "doc"],
    outputFormat: "odt",
    inputMode: "file",
    endpoint: "/api/document/word-to-odt",
    description: "Convert Word files to OpenDocument Text format.",
  },
  {
    id: "word-to-txt",
    name: "Word to Text",
    slug: "word-to-txt",
    category: "document",
    inputFormats: ["docx", "doc"],
    outputFormat: "txt",
    inputMode: "file",
    endpoint: "/api/document/word-to-txt",
    description: "Extract plain text content from Word documents.",
  },
  {
    id: "word-to-html",
    name: "Word to HTML",
    slug: "word-to-html",
    category: "document",
    inputFormats: ["docx", "doc"],
    outputFormat: "html",
    inputMode: "file",
    endpoint: "/api/document/word-to-html",
    description: "Convert Word documents to HTML for web use.",
  },
  {
    id: "odt-to-pdf",
    name: "ODT to PDF",
    slug: "odt-to-pdf",
    category: "document",
    inputFormats: ["odt"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/document/odt-to-pdf",
    description: "Convert OpenDocument Text files to PDF.",
  },
  {
    id: "odt-to-docx",
    name: "ODT to DOCX",
    slug: "odt-to-docx",
    category: "document",
    inputFormats: ["odt"],
    outputFormat: "docx",
    inputMode: "file",
    endpoint: "/api/document/odt-to-docx",
    description: "Convert ODT to Microsoft Word DOCX format.",
  },
  {
    id: "html-to-pdf",
    name: "HTML to PDF",
    slug: "html-to-pdf",
    category: "document",
    inputFormats: ["html", "htm"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/document/html-to-pdf",
    description: "Convert HTML files to PDF using WeasyPrint.",
  },
  {
    id: "md-to-pdf",
    name: "Markdown to PDF",
    slug: "md-to-pdf",
    category: "document",
    inputFormats: ["md", "markdown"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/document/md-to-pdf",
    description: "Convert Markdown files to styled PDF documents.",
    popular: true,
  },
  {
    id: "md-to-html",
    name: "Markdown to HTML",
    slug: "md-to-html",
    category: "document",
    inputFormats: ["md", "markdown"],
    outputFormat: "html",
    inputMode: "file",
    endpoint: "/api/document/md-to-html",
    description: "Convert Markdown to HTML.",
  },
  {
    id: "md-to-docx",
    name: "Markdown to DOCX",
    slug: "md-to-docx",
    category: "document",
    inputFormats: ["md", "markdown"],
    outputFormat: "docx",
    inputMode: "file",
    endpoint: "/api/document/md-to-docx",
    description: "Convert Markdown files to Word DOCX format.",
  },
  {
    id: "txt-to-pdf",
    name: "TXT to PDF",
    slug: "txt-to-pdf",
    category: "document",
    inputFormats: ["txt"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/document/txt-to-pdf",
    description: "Convert plain text files to PDF documents.",
  },
  {
    id: "rtf-to-pdf",
    name: "RTF to PDF",
    slug: "rtf-to-pdf",
    category: "document",
    inputFormats: ["rtf"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/document/rtf-to-pdf",
    description: "Convert Rich Text Format files to PDF.",
  },
  {
    id: "rtf-to-docx",
    name: "RTF to DOCX",
    slug: "rtf-to-docx",
    category: "document",
    inputFormats: ["rtf"],
    outputFormat: "docx",
    inputMode: "file",
    endpoint: "/api/document/rtf-to-docx",
    description: "Convert RTF files to modern Word DOCX format.",
  },
  {
    id: "pages-to-pdf",
    name: "Pages to PDF",
    slug: "pages-to-pdf",
    category: "document",
    inputFormats: ["pages"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/document/pages-to-pdf",
    description: "Convert Apple Pages documents to PDF via LibreOffice.",
  },
  {
    id: "epub-to-pdf-doc",
    name: "EPUB to PDF",
    slug: "epub-to-pdf",
    category: "document",
    inputFormats: ["epub"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/ebook/epub-to-pdf",
    description: "Convert EPUB ebooks to PDF via Calibre.",
    popular: true,
  },
  {
    id: "pptx-to-pdf-doc",
    name: "PPTX to PDF",
    slug: "pptx-to-pdf",
    category: "document",
    inputFormats: ["pptx", "ppt"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/presentation/pptx-to-pdf",
    description: "Convert PowerPoint presentations to PDF.",
    popular: true,
  },
];

// ─── Video Tools (28) ────────────────────────────────────────────────────────

const videoTools: ConverterTool[] = [
  {
    id: "mp4-to-mp3",
    name: "MP4 to MP3",
    slug: "mp4-to-mp3",
    category: "video",
    inputFormats: ["mp4"],
    outputFormat: "mp3",
    inputMode: "file",
    endpoint: "/api/video/mp4-to-mp3",
    description: "Extract the audio track from an MP4 video as MP3.",
    options: [{ key: "bitrate", label: "Bitrate", type: "select", default: "192k", options: ["128k", "192k", "256k", "320k"] }],
    popular: true,
  },
  {
    id: "mp4-to-wav",
    name: "MP4 to WAV",
    slug: "mp4-to-wav",
    category: "video",
    inputFormats: ["mp4"],
    outputFormat: "wav",
    inputMode: "file",
    endpoint: "/api/video/mp4-to-wav",
    description: "Extract audio from MP4 as lossless WAV.",
  },
  {
    id: "mp4-to-gif-video",
    name: "MP4 to GIF",
    slug: "mp4-to-gif",
    category: "video",
    inputFormats: ["mp4"],
    outputFormat: "gif",
    inputMode: "file",
    endpoint: "/api/video/mp4-to-gif",
    description: "Convert a short MP4 clip to an animated GIF.",
    options: [
      { key: "start", label: "Start (s)", type: "number", default: 0, min: 0 },
      { key: "duration", label: "Duration (s)", type: "number", default: 10, min: 1, max: 60 },
      { key: "fps", label: "FPS", type: "select", default: "12", options: ["8", "12", "15", "24"] },
    ],
  },
  {
    id: "mp4-to-webm",
    name: "MP4 to WebM",
    slug: "mp4-to-webm",
    category: "video",
    inputFormats: ["mp4"],
    outputFormat: "webm",
    inputMode: "file",
    endpoint: "/api/video/mp4-to-webm",
    description: "Convert MP4 to open WebM format for web players.",
  },
  {
    id: "mp4-to-avi",
    name: "MP4 to AVI",
    slug: "mp4-to-avi",
    category: "video",
    inputFormats: ["mp4"],
    outputFormat: "avi",
    inputMode: "file",
    endpoint: "/api/video/mp4-to-avi",
    description: "Convert MP4 to legacy AVI container format.",
  },
  {
    id: "mp4-to-mov",
    name: "MP4 to MOV",
    slug: "mp4-to-mov",
    category: "video",
    inputFormats: ["mp4"],
    outputFormat: "mov",
    inputMode: "file",
    endpoint: "/api/video/mp4-to-mov",
    description: "Convert MP4 to Apple QuickTime MOV format.",
  },
  {
    id: "mov-to-mp4",
    name: "MOV to MP4",
    slug: "mov-to-mp4",
    category: "video",
    inputFormats: ["mov"],
    outputFormat: "mp4",
    inputMode: "file",
    endpoint: "/api/video/mov-to-mp4",
    description: "Convert Apple MOV videos to universal MP4 format.",
    popular: true,
  },
  {
    id: "mov-to-mp3",
    name: "MOV to MP3",
    slug: "mov-to-mp3",
    category: "video",
    inputFormats: ["mov"],
    outputFormat: "mp3",
    inputMode: "file",
    endpoint: "/api/video/mov-to-mp3",
    description: "Extract audio from MOV files as MP3.",
    options: [{ key: "bitrate", label: "Bitrate", type: "select", default: "192k", options: ["128k", "192k", "256k", "320k"] }],
  },
  {
    id: "avi-to-mp4",
    name: "AVI to MP4",
    slug: "avi-to-mp4",
    category: "video",
    inputFormats: ["avi"],
    outputFormat: "mp4",
    inputMode: "file",
    endpoint: "/api/video/avi-to-mp4",
    description: "Convert AVI videos to modern MP4 format.",
    popular: true,
  },
  {
    id: "avi-to-mp3",
    name: "AVI to MP3",
    slug: "avi-to-mp3",
    category: "video",
    inputFormats: ["avi"],
    outputFormat: "mp3",
    inputMode: "file",
    endpoint: "/api/video/avi-to-mp3",
    description: "Extract audio from AVI files as MP3.",
    options: [{ key: "bitrate", label: "Bitrate", type: "select", default: "192k", options: ["128k", "192k", "256k", "320k"] }],
  },
  {
    id: "mkv-to-mp4",
    name: "MKV to MP4",
    slug: "mkv-to-mp4",
    category: "video",
    inputFormats: ["mkv"],
    outputFormat: "mp4",
    inputMode: "file",
    endpoint: "/api/video/mkv-to-mp4",
    description: "Convert Matroska MKV files to MP4.",
    popular: true,
  },
  {
    id: "mkv-to-mp3",
    name: "MKV to MP3",
    slug: "mkv-to-mp3",
    category: "video",
    inputFormats: ["mkv"],
    outputFormat: "mp3",
    inputMode: "file",
    endpoint: "/api/video/mkv-to-mp3",
    description: "Extract audio from MKV files as MP3.",
    options: [{ key: "bitrate", label: "Bitrate", type: "select", default: "192k", options: ["128k", "192k", "256k", "320k"] }],
  },
  {
    id: "webm-to-mp4",
    name: "WebM to MP4",
    slug: "webm-to-mp4",
    category: "video",
    inputFormats: ["webm"],
    outputFormat: "mp4",
    inputMode: "file",
    endpoint: "/api/video/webm-to-mp4",
    description: "Convert WebM videos to MP4 format.",
  },
  {
    id: "webm-to-mp3",
    name: "WebM to MP3",
    slug: "webm-to-mp3",
    category: "video",
    inputFormats: ["webm"],
    outputFormat: "mp3",
    inputMode: "file",
    endpoint: "/api/video/webm-to-mp3",
    description: "Extract audio from WebM files as MP3.",
  },
  {
    id: "flv-to-mp4",
    name: "FLV to MP4",
    slug: "flv-to-mp4",
    category: "video",
    inputFormats: ["flv"],
    outputFormat: "mp4",
    inputMode: "file",
    endpoint: "/api/video/flv-to-mp4",
    description: "Convert legacy Flash FLV videos to MP4.",
  },
  {
    id: "wmv-to-mp4",
    name: "WMV to MP4",
    slug: "wmv-to-mp4",
    category: "video",
    inputFormats: ["wmv"],
    outputFormat: "mp4",
    inputMode: "file",
    endpoint: "/api/video/wmv-to-mp4",
    description: "Convert Windows Media Video to MP4.",
  },
  {
    id: "url-to-mp4",
    name: "URL to MP4",
    slug: "url-to-mp4",
    category: "video",
    inputFormats: ["url"],
    outputFormat: "mp4",
    inputMode: "url",
    endpoint: "/api/video/url-to-mp4",
    description: "Download and convert YouTube / web videos to MP4 via yt-dlp.",
    popular: true,
  },
  {
    id: "url-to-mp3",
    name: "URL to MP3",
    slug: "url-to-mp3",
    category: "video",
    inputFormats: ["url"],
    outputFormat: "mp3",
    inputMode: "url",
    endpoint: "/api/video/url-to-mp3",
    description: "Extract audio from YouTube / web videos as MP3 via yt-dlp.",
    options: [{ key: "bitrate", label: "Bitrate", type: "select", default: "192k", options: ["128k", "192k", "256k", "320k"] }],
    popular: true,
  },
  {
    id: "url-to-webm",
    name: "URL to WebM",
    slug: "url-to-webm",
    category: "video",
    inputFormats: ["url"],
    outputFormat: "webm",
    inputMode: "url",
    endpoint: "/api/video/url-to-webm",
    description: "Download and convert web videos to WebM via yt-dlp.",
  },
  {
    id: "video-compress",
    name: "Video Compress",
    slug: "video-compress",
    category: "video",
    inputFormats: ["mp4", "mov", "avi", "mkv", "webm"],
    outputFormat: "mp4",
    inputMode: "file",
    endpoint: "/api/video/compress",
    description: "Reduce video file size using H.264 encoding.",
    options: [{ key: "crf", label: "Quality (CRF)", type: "range", default: 28, min: 18, max: 51 }],
  },
  {
    id: "video-trim",
    name: "Video Trim",
    slug: "video-trim",
    category: "video",
    inputFormats: ["mp4", "mov", "avi", "mkv", "webm"],
    outputFormat: "mp4",
    inputMode: "file",
    endpoint: "/api/video/trim",
    description: "Trim a video to a specific start and end time.",
    options: [
      { key: "start", label: "Start (s)", type: "number", default: 0, min: 0 },
      { key: "end", label: "End (s)", type: "number", default: 30, min: 1 },
    ],
  },
  {
    id: "video-resize",
    name: "Video Resize",
    slug: "video-resize",
    category: "video",
    inputFormats: ["mp4", "mov", "avi", "mkv"],
    outputFormat: "mp4",
    inputMode: "file",
    endpoint: "/api/video/resize",
    description: "Resize a video to specific dimensions.",
    options: [
      { key: "width", label: "Width", type: "number", default: 1280, min: 1, unit: "px" },
      { key: "height", label: "Height", type: "number", default: 720, min: 1, unit: "px" },
    ],
  },
];

// ─── Audio Tools (21) ────────────────────────────────────────────────────────

const audioTools: ConverterTool[] = [
  {
    id: "mp3-to-wav",
    name: "MP3 to WAV",
    slug: "mp3-to-wav",
    category: "audio",
    inputFormats: ["mp3"],
    outputFormat: "wav",
    inputMode: "file",
    endpoint: "/api/audio/mp3-to-wav",
    description: "Convert MP3 audio to lossless WAV format.",
    popular: true,
  },
  {
    id: "mp3-to-flac",
    name: "MP3 to FLAC",
    slug: "mp3-to-flac",
    category: "audio",
    inputFormats: ["mp3"],
    outputFormat: "flac",
    inputMode: "file",
    endpoint: "/api/audio/mp3-to-flac",
    description: "Convert MP3 to lossless FLAC audio.",
  },
  {
    id: "mp3-to-ogg",
    name: "MP3 to OGG",
    slug: "mp3-to-ogg",
    category: "audio",
    inputFormats: ["mp3"],
    outputFormat: "ogg",
    inputMode: "file",
    endpoint: "/api/audio/mp3-to-ogg",
    description: "Convert MP3 to open OGG Vorbis format.",
  },
  {
    id: "mp3-to-aac",
    name: "MP3 to AAC",
    slug: "mp3-to-aac",
    category: "audio",
    inputFormats: ["mp3"],
    outputFormat: "aac",
    inputMode: "file",
    endpoint: "/api/audio/mp3-to-aac",
    description: "Convert MP3 to AAC for Apple device compatibility.",
  },
  {
    id: "mp3-to-m4a",
    name: "MP3 to M4A",
    slug: "mp3-to-m4a",
    category: "audio",
    inputFormats: ["mp3"],
    outputFormat: "m4a",
    inputMode: "file",
    endpoint: "/api/audio/mp3-to-m4a",
    description: "Convert MP3 to M4A format.",
  },
  {
    id: "wav-to-mp3",
    name: "WAV to MP3",
    slug: "wav-to-mp3",
    category: "audio",
    inputFormats: ["wav"],
    outputFormat: "mp3",
    inputMode: "file",
    endpoint: "/api/audio/wav-to-mp3",
    description: "Compress WAV audio to MP3 for smaller file sizes.",
    options: [{ key: "bitrate", label: "Bitrate", type: "select", default: "192k", options: ["128k", "192k", "256k", "320k"] }],
    popular: true,
  },
  {
    id: "wav-to-flac",
    name: "WAV to FLAC",
    slug: "wav-to-flac",
    category: "audio",
    inputFormats: ["wav"],
    outputFormat: "flac",
    inputMode: "file",
    endpoint: "/api/audio/wav-to-flac",
    description: "Convert WAV to lossless compressed FLAC.",
  },
  {
    id: "wav-to-ogg",
    name: "WAV to OGG",
    slug: "wav-to-ogg",
    category: "audio",
    inputFormats: ["wav"],
    outputFormat: "ogg",
    inputMode: "file",
    endpoint: "/api/audio/wav-to-ogg",
    description: "Convert WAV to OGG Vorbis format.",
  },
  {
    id: "flac-to-mp3",
    name: "FLAC to MP3",
    slug: "flac-to-mp3",
    category: "audio",
    inputFormats: ["flac"],
    outputFormat: "mp3",
    inputMode: "file",
    endpoint: "/api/audio/flac-to-mp3",
    description: "Convert lossless FLAC audio to MP3.",
    options: [{ key: "bitrate", label: "Bitrate", type: "select", default: "320k", options: ["128k", "192k", "256k", "320k"] }],
  },
  {
    id: "flac-to-wav",
    name: "FLAC to WAV",
    slug: "flac-to-wav",
    category: "audio",
    inputFormats: ["flac"],
    outputFormat: "wav",
    inputMode: "file",
    endpoint: "/api/audio/flac-to-wav",
    description: "Decode FLAC to uncompressed WAV format.",
  },
  {
    id: "flac-to-ogg",
    name: "FLAC to OGG",
    slug: "flac-to-ogg",
    category: "audio",
    inputFormats: ["flac"],
    outputFormat: "ogg",
    inputMode: "file",
    endpoint: "/api/audio/flac-to-ogg",
    description: "Convert FLAC to OGG Vorbis format.",
  },
  {
    id: "ogg-to-mp3",
    name: "OGG to MP3",
    slug: "ogg-to-mp3",
    category: "audio",
    inputFormats: ["ogg"],
    outputFormat: "mp3",
    inputMode: "file",
    endpoint: "/api/audio/ogg-to-mp3",
    description: "Convert OGG Vorbis audio to MP3.",
  },
  {
    id: "ogg-to-wav",
    name: "OGG to WAV",
    slug: "ogg-to-wav",
    category: "audio",
    inputFormats: ["ogg"],
    outputFormat: "wav",
    inputMode: "file",
    endpoint: "/api/audio/ogg-to-wav",
    description: "Convert OGG audio to uncompressed WAV.",
  },
  {
    id: "aac-to-mp3",
    name: "AAC to MP3",
    slug: "aac-to-mp3",
    category: "audio",
    inputFormats: ["aac"],
    outputFormat: "mp3",
    inputMode: "file",
    endpoint: "/api/audio/aac-to-mp3",
    description: "Convert AAC audio to widely compatible MP3.",
  },
  {
    id: "aac-to-wav",
    name: "AAC to WAV",
    slug: "aac-to-wav",
    category: "audio",
    inputFormats: ["aac"],
    outputFormat: "wav",
    inputMode: "file",
    endpoint: "/api/audio/aac-to-wav",
    description: "Convert AAC to uncompressed WAV audio.",
  },
  {
    id: "m4a-to-mp3",
    name: "M4A to MP3",
    slug: "m4a-to-mp3",
    category: "audio",
    inputFormats: ["m4a"],
    outputFormat: "mp3",
    inputMode: "file",
    endpoint: "/api/audio/m4a-to-mp3",
    description: "Convert M4A audio files to MP3 format.",
    popular: true,
  },
  {
    id: "m4a-to-wav",
    name: "M4A to WAV",
    slug: "m4a-to-wav",
    category: "audio",
    inputFormats: ["m4a"],
    outputFormat: "wav",
    inputMode: "file",
    endpoint: "/api/audio/m4a-to-wav",
    description: "Convert M4A to uncompressed WAV format.",
  },
  {
    id: "wma-to-mp3",
    name: "WMA to MP3",
    slug: "wma-to-mp3",
    category: "audio",
    inputFormats: ["wma"],
    outputFormat: "mp3",
    inputMode: "file",
    endpoint: "/api/audio/wma-to-mp3",
    description: "Convert Windows Media Audio to MP3.",
  },
  {
    id: "audio-trim",
    name: "Audio Trim",
    slug: "audio-trim",
    category: "audio",
    inputFormats: ["mp3", "wav", "flac", "ogg", "m4a", "aac"],
    outputFormat: "mp3",
    inputMode: "file",
    endpoint: "/api/audio/trim",
    description: "Trim audio to a specific start and end time.",
    options: [
      { key: "start", label: "Start (s)", type: "number", default: 0, min: 0 },
      { key: "end", label: "End (s)", type: "number", default: 30, min: 1 },
    ],
  },
  {
    id: "audio-merge",
    name: "Audio Merge",
    slug: "audio-merge",
    category: "audio",
    inputFormats: ["mp3", "wav", "flac", "ogg"],
    outputFormat: "mp3",
    inputMode: "file",
    endpoint: "/api/audio/merge",
    description: "Merge multiple audio files into one track.",
  },
  {
    id: "audio-compress",
    name: "Audio Compress",
    slug: "audio-compress",
    category: "audio",
    inputFormats: ["mp3", "wav", "flac", "ogg", "m4a"],
    outputFormat: "mp3",
    inputMode: "file",
    endpoint: "/api/audio/compress",
    description: "Reduce audio file size by adjusting bitrate.",
    options: [{ key: "bitrate", label: "Bitrate", type: "select", default: "128k", options: ["64k", "96k", "128k", "192k"] }],
  },
];

// ─── Spreadsheet Tools (8) ───────────────────────────────────────────────────

const spreadsheetTools: ConverterTool[] = [
  {
    id: "csv-to-excel",
    name: "CSV to Excel",
    slug: "csv-to-excel",
    category: "spreadsheet",
    inputFormats: ["csv"],
    outputFormat: "xlsx",
    inputMode: "file",
    endpoint: "/api/spreadsheet/csv-to-excel",
    description: "Convert CSV files to Excel XLSX spreadsheets.",
    popular: true,
  },
  {
    id: "csv-to-json",
    name: "CSV to JSON",
    slug: "csv-to-json",
    category: "spreadsheet",
    inputFormats: ["csv"],
    outputFormat: "json",
    inputMode: "file",
    endpoint: "/api/spreadsheet/csv-to-json",
    description: "Convert CSV data to JSON format.",
    popular: true,
  },
  {
    id: "csv-to-html",
    name: "CSV to HTML Table",
    slug: "csv-to-html",
    category: "spreadsheet",
    inputFormats: ["csv"],
    outputFormat: "html",
    inputMode: "file",
    endpoint: "/api/spreadsheet/csv-to-html",
    description: "Convert CSV data to an HTML table.",
  },
  {
    id: "excel-to-csv",
    name: "Excel to CSV",
    slug: "excel-to-csv",
    category: "spreadsheet",
    inputFormats: ["xlsx", "xls"],
    outputFormat: "csv",
    inputMode: "file",
    endpoint: "/api/spreadsheet/excel-to-csv",
    description: "Extract Excel spreadsheet data as CSV.",
    popular: true,
  },
  {
    id: "excel-to-pdf",
    name: "Excel to PDF",
    slug: "excel-to-pdf",
    category: "spreadsheet",
    inputFormats: ["xlsx", "xls"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/spreadsheet/excel-to-pdf",
    description: "Convert Excel spreadsheets to PDF via LibreOffice.",
  },
  {
    id: "excel-to-json",
    name: "Excel to JSON",
    slug: "excel-to-json",
    category: "spreadsheet",
    inputFormats: ["xlsx", "xls"],
    outputFormat: "json",
    inputMode: "file",
    endpoint: "/api/spreadsheet/excel-to-json",
    description: "Convert Excel data to JSON format.",
  },
  {
    id: "ods-to-xlsx",
    name: "ODS to XLSX",
    slug: "ods-to-xlsx",
    category: "spreadsheet",
    inputFormats: ["ods"],
    outputFormat: "xlsx",
    inputMode: "file",
    endpoint: "/api/spreadsheet/ods-to-xlsx",
    description: "Convert OpenDocument Spreadsheet to Excel XLSX.",
  },
  {
    id: "xlsx-to-ods",
    name: "XLSX to ODS",
    slug: "xlsx-to-ods",
    category: "spreadsheet",
    inputFormats: ["xlsx"],
    outputFormat: "ods",
    inputMode: "file",
    endpoint: "/api/spreadsheet/xlsx-to-ods",
    description: "Convert Excel XLSX to OpenDocument Spreadsheet format.",
  },
];

// ─── Presentation Tools (11) ─────────────────────────────────────────────────

const presentationTools: ConverterTool[] = [
  {
    id: "pptx-to-pdf",
    name: "PPTX to PDF",
    slug: "pptx-to-pdf",
    category: "presentation",
    inputFormats: ["pptx", "ppt"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/presentation/pptx-to-pdf",
    description: "Convert PowerPoint presentations to PDF.",
    popular: true,
  },
  {
    id: "pptx-to-images",
    name: "PPTX to Images",
    slug: "pptx-to-images",
    category: "presentation",
    inputFormats: ["pptx", "ppt"],
    outputFormat: "zip",
    inputMode: "file",
    endpoint: "/api/presentation/pptx-to-images",
    description: "Convert each presentation slide to a PNG image.",
    options: [
      { key: "dpi", label: "DPI", type: "select", default: "150", options: ["96", "150", "300"], unit: "dpi" },
    ],
  },
  {
    id: "pptx-to-html",
    name: "PPTX to HTML",
    slug: "pptx-to-html",
    category: "presentation",
    inputFormats: ["pptx"],
    outputFormat: "html",
    inputMode: "file",
    endpoint: "/api/presentation/pptx-to-html",
    description: "Convert PowerPoint to HTML for browser playback.",
  },
  {
    id: "ppt-to-pptx",
    name: "PPT to PPTX",
    slug: "ppt-to-pptx",
    category: "presentation",
    inputFormats: ["ppt"],
    outputFormat: "pptx",
    inputMode: "file",
    endpoint: "/api/presentation/ppt-to-pptx",
    description: "Upgrade legacy PPT files to modern PPTX format.",
  },
  {
    id: "ppt-to-pdf",
    name: "PPT to PDF",
    slug: "ppt-to-pdf",
    category: "presentation",
    inputFormats: ["ppt"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/presentation/ppt-to-pdf",
    description: "Convert legacy PPT files to PDF.",
  },
  {
    id: "odp-to-pptx",
    name: "ODP to PPTX",
    slug: "odp-to-pptx",
    category: "presentation",
    inputFormats: ["odp"],
    outputFormat: "pptx",
    inputMode: "file",
    endpoint: "/api/presentation/odp-to-pptx",
    description: "Convert OpenDocument Presentation to PowerPoint.",
  },
  {
    id: "odp-to-pdf",
    name: "ODP to PDF",
    slug: "odp-to-pdf",
    category: "presentation",
    inputFormats: ["odp"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/presentation/odp-to-pdf",
    description: "Convert ODP presentations to PDF.",
  },
  {
    id: "key-to-pdf",
    name: "Keynote to PDF",
    slug: "key-to-pdf",
    category: "presentation",
    inputFormats: ["key"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/presentation/key-to-pdf",
    description: "Convert Apple Keynote files to PDF via LibreOffice.",
  },
  {
    id: "pdf-to-pptx",
    name: "PDF to PPTX",
    slug: "pdf-to-pptx",
    category: "presentation",
    inputFormats: ["pdf"],
    outputFormat: "pptx",
    inputMode: "file",
    endpoint: "/api/presentation/pdf-to-pptx",
    description: "Convert PDF to PowerPoint PPTX (basic conversion).",
  },
  {
    id: "pptx-compress",
    name: "PPTX Compress",
    slug: "pptx-compress",
    category: "presentation",
    inputFormats: ["pptx"],
    outputFormat: "pptx",
    inputMode: "file",
    endpoint: "/api/presentation/compress",
    description: "Reduce PPTX file size by compressing embedded images.",
  },
  {
    id: "pptx-merge",
    name: "PPTX Merge",
    slug: "pptx-merge",
    category: "presentation",
    inputFormats: ["pptx"],
    outputFormat: "pptx",
    inputMode: "file",
    endpoint: "/api/presentation/merge",
    description: "Combine multiple PowerPoint files into one presentation.",
  },
];

// ─── eBook Tools (22) ────────────────────────────────────────────────────────

const ebookTools: ConverterTool[] = [
  {
    id: "epub-to-mobi",
    name: "EPUB to MOBI",
    slug: "epub-to-mobi",
    category: "ebook",
    inputFormats: ["epub"],
    outputFormat: "mobi",
    inputMode: "file",
    endpoint: "/api/ebook/epub-to-mobi",
    description: "Convert EPUB ebooks to Kindle MOBI format.",
    popular: true,
  },
  {
    id: "epub-to-pdf",
    name: "EPUB to PDF",
    slug: "epub-to-pdf",
    category: "ebook",
    inputFormats: ["epub"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/ebook/epub-to-pdf",
    description: "Convert EPUB ebooks to PDF via Calibre.",
    popular: true,
  },
  {
    id: "epub-to-txt",
    name: "EPUB to TXT",
    slug: "epub-to-txt",
    category: "ebook",
    inputFormats: ["epub"],
    outputFormat: "txt",
    inputMode: "file",
    endpoint: "/api/ebook/epub-to-txt",
    description: "Extract plain text from EPUB ebooks.",
  },
  {
    id: "epub-to-html",
    name: "EPUB to HTML",
    slug: "epub-to-html",
    category: "ebook",
    inputFormats: ["epub"],
    outputFormat: "html",
    inputMode: "file",
    endpoint: "/api/ebook/epub-to-html",
    description: "Convert EPUB to HTML for browser reading.",
  },
  {
    id: "epub-to-docx",
    name: "EPUB to DOCX",
    slug: "epub-to-docx",
    category: "ebook",
    inputFormats: ["epub"],
    outputFormat: "docx",
    inputMode: "file",
    endpoint: "/api/ebook/epub-to-docx",
    description: "Convert EPUB ebooks to editable Word DOCX.",
  },
  {
    id: "mobi-to-epub",
    name: "MOBI to EPUB",
    slug: "mobi-to-epub",
    category: "ebook",
    inputFormats: ["mobi"],
    outputFormat: "epub",
    inputMode: "file",
    endpoint: "/api/ebook/mobi-to-epub",
    description: "Convert Kindle MOBI ebooks to open EPUB format.",
    popular: true,
  },
  {
    id: "mobi-to-pdf",
    name: "MOBI to PDF",
    slug: "mobi-to-pdf",
    category: "ebook",
    inputFormats: ["mobi"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/ebook/mobi-to-pdf",
    description: "Convert MOBI ebooks to PDF.",
  },
  {
    id: "azw3-to-epub",
    name: "AZW3 to EPUB",
    slug: "azw3-to-epub",
    category: "ebook",
    inputFormats: ["azw3", "azw"],
    outputFormat: "epub",
    inputMode: "file",
    endpoint: "/api/ebook/azw3-to-epub",
    description: "Convert Kindle AZW3 ebooks to EPUB.",
  },
  {
    id: "azw3-to-mobi",
    name: "AZW3 to MOBI",
    slug: "azw3-to-mobi",
    category: "ebook",
    inputFormats: ["azw3", "azw"],
    outputFormat: "mobi",
    inputMode: "file",
    endpoint: "/api/ebook/azw3-to-mobi",
    description: "Convert AZW3 to MOBI format.",
  },
  {
    id: "fb2-to-epub",
    name: "FB2 to EPUB",
    slug: "fb2-to-epub",
    category: "ebook",
    inputFormats: ["fb2"],
    outputFormat: "epub",
    inputMode: "file",
    endpoint: "/api/ebook/fb2-to-epub",
    description: "Convert FictionBook 2 to EPUB.",
  },
  {
    id: "fb2-to-pdf",
    name: "FB2 to PDF",
    slug: "fb2-to-pdf",
    category: "ebook",
    inputFormats: ["fb2"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/ebook/fb2-to-pdf",
    description: "Convert FictionBook 2 to PDF.",
  },
  {
    id: "lit-to-epub",
    name: "LIT to EPUB",
    slug: "lit-to-epub",
    category: "ebook",
    inputFormats: ["lit"],
    outputFormat: "epub",
    inputMode: "file",
    endpoint: "/api/ebook/lit-to-epub",
    description: "Convert Microsoft LIT ebooks to EPUB.",
  },
  {
    id: "prc-to-epub",
    name: "PRC to EPUB",
    slug: "prc-to-epub",
    category: "ebook",
    inputFormats: ["prc"],
    outputFormat: "epub",
    inputMode: "file",
    endpoint: "/api/ebook/prc-to-epub",
    description: "Convert PRC ebooks to EPUB.",
  },
  {
    id: "html-to-epub",
    name: "HTML to EPUB",
    slug: "html-to-epub",
    category: "ebook",
    inputFormats: ["html", "htm"],
    outputFormat: "epub",
    inputMode: "file",
    endpoint: "/api/ebook/html-to-epub",
    description: "Package HTML content as an EPUB ebook.",
  },
  {
    id: "docx-to-epub",
    name: "DOCX to EPUB",
    slug: "docx-to-epub",
    category: "ebook",
    inputFormats: ["docx"],
    outputFormat: "epub",
    inputMode: "file",
    endpoint: "/api/ebook/docx-to-epub",
    description: "Convert Word DOCX to EPUB ebook format.",
  },
  {
    id: "txt-to-epub",
    name: "TXT to EPUB",
    slug: "txt-to-epub",
    category: "ebook",
    inputFormats: ["txt"],
    outputFormat: "epub",
    inputMode: "file",
    endpoint: "/api/ebook/txt-to-epub",
    description: "Convert plain text to EPUB ebook format.",
  },
  {
    id: "pdf-to-epub",
    name: "PDF to EPUB",
    slug: "pdf-to-epub",
    category: "ebook",
    inputFormats: ["pdf"],
    outputFormat: "epub",
    inputMode: "file",
    endpoint: "/api/ebook/pdf-to-epub",
    description: "Convert PDF documents to EPUB ebook format.",
  },
  {
    id: "epub-metadata",
    name: "EPUB Metadata Editor",
    slug: "epub-metadata",
    category: "ebook",
    inputFormats: ["epub"],
    outputFormat: "epub",
    inputMode: "file",
    endpoint: "/api/ebook/epub-metadata",
    description: "Edit title, author, and cover of EPUB ebooks.",
    options: [
      { key: "title", label: "Title", type: "toggle", default: "" },
      { key: "author", label: "Author", type: "toggle", default: "" },
    ],
  },
  {
    id: "epub-split",
    name: "EPUB Split",
    slug: "epub-split",
    category: "ebook",
    inputFormats: ["epub"],
    outputFormat: "zip",
    inputMode: "file",
    endpoint: "/api/ebook/epub-split",
    description: "Split an EPUB into individual chapter files.",
  },
  {
    id: "epub-merge",
    name: "EPUB Merge",
    slug: "epub-merge",
    category: "ebook",
    inputFormats: ["epub"],
    outputFormat: "epub",
    inputMode: "file",
    endpoint: "/api/ebook/epub-merge",
    description: "Combine multiple EPUB files into one ebook.",
  },
];

// ─── Archive Tools (14) ──────────────────────────────────────────────────────

const archiveTools: ConverterTool[] = [
  {
    id: "zip-extract",
    name: "ZIP Extract",
    slug: "zip-extract",
    category: "archive",
    inputFormats: ["zip"],
    outputFormat: "zip",
    inputMode: "file",
    endpoint: "/api/archive/extract",
    description: "Extract files from a ZIP archive.",
    popular: true,
  },
  {
    id: "zip-to-tar-gz",
    name: "ZIP to TAR.GZ",
    slug: "zip-to-tar-gz",
    category: "archive",
    inputFormats: ["zip"],
    outputFormat: "tar.gz",
    inputMode: "file",
    endpoint: "/api/archive/zip-to-tar",
    description: "Convert ZIP archive to TAR.GZ format.",
  },
  {
    id: "zip-to-7z",
    name: "ZIP to 7Z",
    slug: "zip-to-7z",
    category: "archive",
    inputFormats: ["zip"],
    outputFormat: "7z",
    inputMode: "file",
    endpoint: "/api/archive/zip-to-7z",
    description: "Convert ZIP archive to 7-Zip format.",
  },
  {
    id: "rar-extract",
    name: "RAR Extract",
    slug: "rar-extract",
    category: "archive",
    inputFormats: ["rar"],
    outputFormat: "zip",
    inputMode: "file",
    endpoint: "/api/archive/extract",
    description: "Extract files from a RAR archive.",
  },
  {
    id: "rar-to-zip",
    name: "RAR to ZIP",
    slug: "rar-to-zip",
    category: "archive",
    inputFormats: ["rar"],
    outputFormat: "zip",
    inputMode: "file",
    endpoint: "/api/archive/rar-to-zip",
    description: "Convert RAR archive to universally compatible ZIP.",
  },
  {
    id: "7z-extract",
    name: "7Z Extract",
    slug: "7z-extract",
    category: "archive",
    inputFormats: ["7z"],
    outputFormat: "zip",
    inputMode: "file",
    endpoint: "/api/archive/extract",
    description: "Extract files from a 7-Zip archive.",
  },
  {
    id: "7z-to-zip",
    name: "7Z to ZIP",
    slug: "7z-to-zip",
    category: "archive",
    inputFormats: ["7z"],
    outputFormat: "zip",
    inputMode: "file",
    endpoint: "/api/archive/7z-to-zip",
    description: "Convert 7Z archive to ZIP format.",
  },
  {
    id: "tar-extract",
    name: "TAR Extract",
    slug: "tar-extract",
    category: "archive",
    inputFormats: ["tar"],
    outputFormat: "zip",
    inputMode: "file",
    endpoint: "/api/archive/extract",
    description: "Extract files from a TAR archive.",
  },
  {
    id: "tar-gz-extract",
    name: "TAR.GZ Extract",
    slug: "tar-gz-extract",
    category: "archive",
    inputFormats: ["tar.gz", "tgz"],
    outputFormat: "zip",
    inputMode: "file",
    endpoint: "/api/archive/extract",
    description: "Extract files from a TAR.GZ archive.",
  },
  {
    id: "create-zip",
    name: "Create ZIP",
    slug: "create-zip",
    category: "archive",
    inputFormats: ["*"],
    outputFormat: "zip",
    inputMode: "file",
    endpoint: "/api/archive/create-zip",
    description: "Bundle multiple files into a single ZIP archive.",
    popular: true,
  },
  {
    id: "create-tar-gz",
    name: "Create TAR.GZ",
    slug: "create-tar-gz",
    category: "archive",
    inputFormats: ["*"],
    outputFormat: "tar.gz",
    inputMode: "file",
    endpoint: "/api/archive/create-tar-gz",
    description: "Bundle multiple files into a TAR.GZ archive.",
  },
  {
    id: "create-7z",
    name: "Create 7Z",
    slug: "create-7z",
    category: "archive",
    inputFormats: ["*"],
    outputFormat: "7z",
    inputMode: "file",
    endpoint: "/api/archive/create-7z",
    description: "Bundle multiple files into a 7-Zip archive.",
  },
  {
    id: "archive-inspect",
    name: "Archive Inspect",
    slug: "archive-inspect",
    category: "archive",
    inputFormats: ["zip", "tar", "tar.gz", "7z"],
    outputFormat: "json",
    inputMode: "file",
    endpoint: "/api/archive/inspect",
    description: "List the contents of an archive without extracting.",
  },
  {
    id: "tar-bz2-extract",
    name: "TAR.BZ2 Extract",
    slug: "tar-bz2-extract",
    category: "archive",
    inputFormats: ["tar.bz2", "tbz2"],
    outputFormat: "zip",
    inputMode: "file",
    endpoint: "/api/archive/extract",
    description: "Extract files from a TAR.BZ2 archive.",
  },
];

// ─── Vector Tools (10) ───────────────────────────────────────────────────────

const vectorTools: ConverterTool[] = [
  {
    id: "svg-to-pdf-vec",
    name: "SVG to PDF",
    slug: "svg-to-pdf",
    category: "vector",
    inputFormats: ["svg"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/vector/svg-to-pdf",
    description: "Convert SVG vector graphics to PDF.",
    popular: true,
  },
  {
    id: "svg-to-png-vec",
    name: "SVG to PNG",
    slug: "svg-to-png",
    category: "vector",
    inputFormats: ["svg"],
    outputFormat: "png",
    inputMode: "file",
    endpoint: "/api/vector/svg-to-png",
    description: "Rasterize SVG to PNG at any resolution.",
    options: [
      { key: "scale", label: "Scale", type: "select", default: "2", options: ["1", "2", "3", "4"] },
    ],
  },
  {
    id: "svg-to-eps",
    name: "SVG to EPS",
    slug: "svg-to-eps",
    category: "vector",
    inputFormats: ["svg"],
    outputFormat: "eps",
    inputMode: "file",
    endpoint: "/api/vector/svg-to-eps",
    description: "Convert SVG to EPS for professional print.",
  },
  {
    id: "eps-to-pdf",
    name: "EPS to PDF",
    slug: "eps-to-pdf",
    category: "vector",
    inputFormats: ["eps"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/vector/eps-to-pdf",
    description: "Convert EPS vector graphics to PDF.",
  },
  {
    id: "eps-to-png",
    name: "EPS to PNG",
    slug: "eps-to-png",
    category: "vector",
    inputFormats: ["eps"],
    outputFormat: "png",
    inputMode: "file",
    endpoint: "/api/vector/eps-to-png",
    description: "Rasterize EPS to PNG via Inkscape.",
  },
  {
    id: "eps-to-svg",
    name: "EPS to SVG",
    slug: "eps-to-svg",
    category: "vector",
    inputFormats: ["eps"],
    outputFormat: "svg",
    inputMode: "file",
    endpoint: "/api/vector/eps-to-svg",
    description: "Convert EPS files to SVG vector format.",
  },
  {
    id: "ai-to-svg",
    name: "AI to SVG",
    slug: "ai-to-svg",
    category: "vector",
    inputFormats: ["ai"],
    outputFormat: "svg",
    inputMode: "file",
    endpoint: "/api/vector/ai-to-svg",
    description: "Convert Adobe Illustrator AI files to SVG via Inkscape.",
  },
  {
    id: "ai-to-pdf",
    name: "AI to PDF",
    slug: "ai-to-pdf",
    category: "vector",
    inputFormats: ["ai"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/vector/ai-to-pdf",
    description: "Convert Adobe Illustrator files to PDF.",
  },
  {
    id: "pdf-to-svg",
    name: "PDF to SVG",
    slug: "pdf-to-svg",
    category: "vector",
    inputFormats: ["pdf"],
    outputFormat: "svg",
    inputMode: "file",
    endpoint: "/api/vector/pdf-to-svg",
    description: "Convert PDF documents to SVG vector format.",
  },
  {
    id: "svg-optimize",
    name: "SVG Optimize",
    slug: "svg-optimize",
    category: "vector",
    inputFormats: ["svg"],
    outputFormat: "svg",
    inputMode: "file",
    endpoint: "/api/vector/svg-optimize",
    description: "Minify and optimize SVG files using scour.",
  },
];

// ─── CAD Tools (9) ───────────────────────────────────────────────────────────

const cadTools: ConverterTool[] = [
  {
    id: "dxf-to-png",
    name: "DXF to PNG",
    slug: "dxf-to-png",
    category: "cad",
    inputFormats: ["dxf"],
    outputFormat: "png",
    inputMode: "file",
    endpoint: "/api/cad/dxf-to-png",
    description: "Render DXF CAD drawings to PNG images.",
    options: [
      { key: "dpi", label: "DPI", type: "select", default: "150", options: ["96", "150", "300"], unit: "dpi" },
    ],
  },
  {
    id: "dxf-to-svg",
    name: "DXF to SVG",
    slug: "dxf-to-svg",
    category: "cad",
    inputFormats: ["dxf"],
    outputFormat: "svg",
    inputMode: "file",
    endpoint: "/api/cad/dxf-to-svg",
    description: "Convert DXF drawings to scalable SVG format.",
  },
  {
    id: "dxf-to-pdf",
    name: "DXF to PDF",
    slug: "dxf-to-pdf",
    category: "cad",
    inputFormats: ["dxf"],
    outputFormat: "pdf",
    inputMode: "file",
    endpoint: "/api/cad/dxf-to-pdf",
    description: "Convert DXF CAD drawings to PDF documents.",
  },
  {
    id: "dwg-to-dxf",
    name: "DWG to DXF",
    slug: "dwg-to-dxf",
    category: "cad",
    inputFormats: ["dwg"],
    outputFormat: "dxf",
    inputMode: "file",
    endpoint: "/api/cad/dwg-to-dxf",
    description: "Convert DWG to open DXF format via ezdxf proxy.",
  },
  {
    id: "stl-to-obj",
    name: "STL to OBJ",
    slug: "stl-to-obj",
    category: "cad",
    inputFormats: ["stl"],
    outputFormat: "obj",
    inputMode: "file",
    endpoint: "/api/cad/stl-to-obj",
    description: "Convert STL 3D models to OBJ format.",
  },
  {
    id: "obj-to-stl",
    name: "OBJ to STL",
    slug: "obj-to-stl",
    category: "cad",
    inputFormats: ["obj"],
    outputFormat: "stl",
    inputMode: "file",
    endpoint: "/api/cad/obj-to-stl",
    description: "Convert OBJ 3D models to STL format for 3D printing.",
  },
  {
    id: "dxf-inspect",
    name: "DXF Inspect",
    slug: "dxf-inspect",
    category: "cad",
    inputFormats: ["dxf"],
    outputFormat: "json",
    inputMode: "file",
    endpoint: "/api/cad/inspect",
    description: "Inspect DXF file geometry and entity summary.",
  },
  {
    id: "svg-to-dxf",
    name: "SVG to DXF",
    slug: "svg-to-dxf",
    category: "cad",
    inputFormats: ["svg"],
    outputFormat: "dxf",
    inputMode: "file",
    endpoint: "/api/cad/svg-to-dxf",
    description: "Convert SVG paths to DXF format for CAD software.",
  },
];

// ─── Font Tools (6) ──────────────────────────────────────────────────────────

const fontTools: ConverterTool[] = [
  {
    id: "ttf-to-otf",
    name: "TTF to OTF",
    slug: "ttf-to-otf",
    category: "font",
    inputFormats: ["ttf"],
    outputFormat: "otf",
    inputMode: "file",
    endpoint: "/api/font/ttf-to-otf",
    description: "Convert TrueType fonts to OpenType format.",
  },
  {
    id: "ttf-to-woff",
    name: "TTF to WOFF",
    slug: "ttf-to-woff",
    category: "font",
    inputFormats: ["ttf"],
    outputFormat: "woff",
    inputMode: "file",
    endpoint: "/api/font/ttf-to-woff",
    description: "Convert TTF to WOFF for web font use.",
    popular: true,
  },
  {
    id: "ttf-to-woff2",
    name: "TTF to WOFF2",
    slug: "ttf-to-woff2",
    category: "font",
    inputFormats: ["ttf"],
    outputFormat: "woff2",
    inputMode: "file",
    endpoint: "/api/font/ttf-to-woff2",
    description: "Convert TTF to WOFF2 for optimal web font compression.",
    popular: true,
  },
  {
    id: "otf-to-ttf",
    name: "OTF to TTF",
    slug: "otf-to-ttf",
    category: "font",
    inputFormats: ["otf"],
    outputFormat: "ttf",
    inputMode: "file",
    endpoint: "/api/font/otf-to-ttf",
    description: "Convert OpenType fonts to TrueType format.",
  },
  {
    id: "otf-to-woff",
    name: "OTF to WOFF",
    slug: "otf-to-woff",
    category: "font",
    inputFormats: ["otf"],
    outputFormat: "woff",
    inputMode: "file",
    endpoint: "/api/font/otf-to-woff",
    description: "Convert OTF to WOFF for web font embedding.",
  },
  {
    id: "woff-to-ttf",
    name: "WOFF to TTF",
    slug: "woff-to-ttf",
    category: "font",
    inputFormats: ["woff"],
    outputFormat: "ttf",
    inputMode: "file",
    endpoint: "/api/font/woff-to-ttf",
    description: "Convert WOFF web fonts back to TTF format.",
  },
];

// ─── Code & Data Tools (14) ──────────────────────────────────────────────────

const codeDataTools: ConverterTool[] = [
  {
    id: "markdown-preview",
    name: "Markdown Previewer",
    slug: "markdown-preview",
    category: "code-data",
    inputFormats: ["md", "markdown"],
    outputFormat: "html",
    inputMode: "text",
    endpoint: "",
    description: "Live Markdown editor with real-time HTML preview. Runs entirely in your browser.",
    popular: true,
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    slug: "json-formatter",
    category: "code-data",
    inputFormats: ["json"],
    outputFormat: "json",
    inputMode: "text",
    endpoint: "/api/code/json-format",
    description: "Prettify or minify JSON data.",
    options: [
      { key: "indent", label: "Indent", type: "select", default: "2", options: ["2", "4"] },
      { key: "minify", label: "Minify", type: "toggle", default: false },
    ],
    popular: true,
  },
  {
    id: "json-to-csv",
    name: "JSON to CSV",
    slug: "json-to-csv",
    category: "code-data",
    inputFormats: ["json"],
    outputFormat: "csv",
    inputMode: "file",
    endpoint: "/api/code/json-to-csv",
    description: "Convert JSON arrays to CSV spreadsheets.",
    popular: true,
  },
  {
    id: "json-to-xml",
    name: "JSON to XML",
    slug: "json-to-xml",
    category: "code-data",
    inputFormats: ["json"],
    outputFormat: "xml",
    inputMode: "file",
    endpoint: "/api/code/json-to-xml",
    description: "Convert JSON to XML format.",
  },
  {
    id: "json-to-yaml",
    name: "JSON to YAML",
    slug: "json-to-yaml",
    category: "code-data",
    inputFormats: ["json"],
    outputFormat: "yaml",
    inputMode: "file",
    endpoint: "/api/code/json-to-yaml",
    description: "Convert JSON to human-readable YAML.",
  },
  {
    id: "csv-to-json-code",
    name: "CSV to JSON",
    slug: "csv-to-json",
    category: "code-data",
    inputFormats: ["csv"],
    outputFormat: "json",
    inputMode: "file",
    endpoint: "/api/code/csv-to-json",
    description: "Convert CSV data to JSON format.",
    popular: true,
  },
  {
    id: "xml-to-json",
    name: "XML to JSON",
    slug: "xml-to-json",
    category: "code-data",
    inputFormats: ["xml"],
    outputFormat: "json",
    inputMode: "file",
    endpoint: "/api/code/xml-to-json",
    description: "Convert XML to JSON format.",
  },
  {
    id: "yaml-to-json",
    name: "YAML to JSON",
    slug: "yaml-to-json",
    category: "code-data",
    inputFormats: ["yaml", "yml"],
    outputFormat: "json",
    inputMode: "file",
    endpoint: "/api/code/yaml-to-json",
    description: "Convert YAML config files to JSON.",
  },
  {
    id: "base64-encode",
    name: "Base64 Encode",
    slug: "base64-encode",
    category: "code-data",
    inputFormats: ["*"],
    outputFormat: "txt",
    inputMode: "file-and-url",
    endpoint: "/api/code/base64-encode",
    description: "Encode text or files to Base64 format.",
    popular: true,
  },
  {
    id: "base64-decode",
    name: "Base64 Decode",
    slug: "base64-decode",
    category: "code-data",
    inputFormats: ["txt"],
    outputFormat: "txt",
    inputMode: "text",
    endpoint: "/api/code/base64-decode",
    description: "Decode Base64 strings back to text or binary.",
  },
  {
    id: "svg-to-code",
    name: "SVG to Code",
    slug: "svg-to-code",
    category: "code-data",
    inputFormats: ["svg"],
    outputFormat: "txt",
    inputMode: "file",
    endpoint: "/api/code/svg-to-code",
    description: "View and copy the SVG source code of an image.",
  },
  {
    id: "code-to-svg",
    name: "Code to SVG",
    slug: "code-to-svg",
    category: "code-data",
    inputFormats: ["txt"],
    outputFormat: "svg",
    inputMode: "text",
    endpoint: "/api/code/code-to-svg",
    description: "Render SVG code as a downloadable SVG file.",
  },
  {
    id: "html-formatter",
    name: "HTML Formatter",
    slug: "html-formatter",
    category: "code-data",
    inputFormats: ["html"],
    outputFormat: "html",
    inputMode: "text",
    endpoint: "/api/code/html-format",
    description: "Prettify and format HTML source code.",
  },
  {
    id: "html-to-pdf-code",
    name: "HTML to PDF",
    slug: "html-to-pdf",
    category: "code-data",
    inputFormats: ["html"],
    outputFormat: "pdf",
    inputMode: "text",
    endpoint: "/api/document/html-to-pdf",
    description: "Render HTML markup as a PDF document.",
  },
];

// ─── Hash Tools (4) ──────────────────────────────────────────────────────────

const hashTools: ConverterTool[] = [
  {
    id: "md5",
    name: "MD5 Hash",
    slug: "md5",
    category: "hash",
    inputFormats: ["*"],
    outputFormat: "txt",
    inputMode: "file",
    endpoint: "",
    description: "Compute MD5 checksum of a file — runs entirely in your browser.",
  },
  {
    id: "sha1",
    name: "SHA-1 Hash",
    slug: "sha1",
    category: "hash",
    inputFormats: ["*"],
    outputFormat: "txt",
    inputMode: "file",
    endpoint: "",
    description: "Compute SHA-1 checksum of a file — runs entirely in your browser.",
  },
  {
    id: "sha256",
    name: "SHA-256 Hash",
    slug: "sha256",
    category: "hash",
    inputFormats: ["*"],
    outputFormat: "txt",
    inputMode: "file",
    endpoint: "",
    description: "Compute SHA-256 checksum of a file — runs entirely in your browser.",
    popular: true,
  },
  {
    id: "sha512",
    name: "SHA-512 Hash",
    slug: "sha512",
    category: "hash",
    inputFormats: ["*"],
    outputFormat: "txt",
    inputMode: "file",
    endpoint: "",
    description: "Compute SHA-512 checksum of a file — runs entirely in your browser.",
  },
];

// ─── All Tools Flat Array ─────────────────────────────────────────────────────

export const allTools: ConverterTool[] = [
  ...imageTools,
  ...documentTools,
  ...videoTools,
  ...audioTools,
  ...spreadsheetTools,
  ...presentationTools,
  ...ebookTools,
  ...archiveTools,
  ...vectorTools,
  ...cadTools,
  ...fontTools,
  ...codeDataTools,
  ...hashTools,
];

// ─── Category Metadata ────────────────────────────────────────────────────────

export const categories: ConverterCategoryMeta[] = [
  {
    id: "image",
    label: "Image",
    slug: "image",
    description: "Convert between all major image formats. HEIC, WebP, PNG, JPG, SVG, GIF and more.",
    icon: "🖼️",
    tools: imageTools,
  },
  {
    id: "document",
    label: "Document",
    slug: "document",
    description: "PDF, Word, HTML, Markdown and more — every document format covered.",
    icon: "📄",
    tools: documentTools,
  },
  {
    id: "video",
    label: "Video",
    slug: "video",
    description: "Convert, compress, trim and download videos. MP4, MOV, MKV, WebM and more.",
    icon: "🎬",
    tools: videoTools,
  },
  {
    id: "audio",
    label: "Audio",
    slug: "audio",
    description: "Convert between MP3, WAV, FLAC, OGG, AAC and more audio formats.",
    icon: "🎵",
    tools: audioTools,
  },
  {
    id: "spreadsheet",
    label: "Spreadsheet",
    slug: "spreadsheet",
    description: "Convert CSV, Excel XLSX, JSON and ODS spreadsheet formats.",
    icon: "📊",
    tools: spreadsheetTools,
  },
  {
    id: "presentation",
    label: "Presentation",
    slug: "presentation",
    description: "Convert PowerPoint, Keynote and OpenDocument presentation formats.",
    icon: "📽️",
    tools: presentationTools,
  },
  {
    id: "ebook",
    label: "eBook",
    slug: "ebook",
    description: "Convert EPUB, MOBI, AZW3, FB2 and more ebook formats via Calibre.",
    icon: "📚",
    tools: ebookTools,
  },
  {
    id: "archive",
    label: "Archive",
    slug: "archive",
    description: "Extract and create ZIP, TAR.GZ, 7Z, RAR and more archive formats.",
    icon: "🗜️",
    tools: archiveTools,
  },
  {
    id: "vector",
    label: "Vector",
    slug: "vector",
    description: "Convert between SVG, EPS, AI and PDF vector graphic formats.",
    icon: "✏️",
    tools: vectorTools,
  },
  {
    id: "cad",
    label: "CAD",
    slug: "cad",
    description: "Convert DXF, DWG, STL and OBJ CAD and 3D model files.",
    icon: "📐",
    tools: cadTools,
  },
  {
    id: "font",
    label: "Font",
    slug: "font",
    description: "Convert between TTF, OTF, WOFF and WOFF2 font formats.",
    icon: "🔤",
    tools: fontTools,
  },
  {
    id: "code-data",
    label: "Code & Data",
    slug: "code-data",
    description: "Format and convert JSON, CSV, XML, YAML, Base64 and HTML.",
    icon: "💻",
    tools: codeDataTools,
  },
  {
    id: "hash",
    label: "Hash",
    slug: "hash",
    description: "Compute MD5, SHA-1, SHA-256 and SHA-512 checksums. Runs in your browser — zero upload.",
    icon: "#️⃣",
    tools: hashTools,
  },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getToolBySlug(categorySlug: string, toolSlug: string): ConverterTool | undefined {
  const cat = categories.find((c) => c.slug === categorySlug);
  return cat?.tools.find((t) => t.slug === toolSlug);
}

export function getCategoryBySlug(slug: string): ConverterCategoryMeta | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getPopularTools(limit = 12): ConverterTool[] {
  return allTools.filter((t) => t.popular).slice(0, limit);
}
